# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:

- stage: Build
  jobs:
  - job: Build_springboot_app
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: '02-todo-web-application-h2/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: WebappTemplate
  jobs:
  - job: App_Service_Json
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/templates'
        Contents: '**/*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        
- stage: CreateWebapp
  jobs:
  - deployment: CreateWebapp
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'FreeOneYear(5f7292bd-e975-43ef-aa61-1871cb2a573d)'
              subscriptionId: '5f7292bd-e975-43ef-aa61-1871cb2a573d'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resourceGroup)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/drop/webapp-sb.json'
              csmParametersFile: '$(Pipeline.Workspace)/drop/webapp-sb.parameters.json'
              overrideParameters: '-hostingPlanName $(hostingPlanName) -location $(location) -webSiteName $(webSiteName) -skuName $(skuName)'
              deploymentMode: 'Incremental'
# - stage: DeployToWebapp
#   jobs:
#   - deployment: DeployToWebapp
#     environment: Production
#     strategy:
#       runOnce:
#         deploy:
#           steps:
